project_id = "tutlimtasnjabdfhpewu"

[functions.netlinking-webhook]
verify_jwt = false

[functions.cron-netlinking-monitor]
verify_jwt = false


[functions.wp-test-connection]
verify_jwt = false

[functions.bot-prerender-check]
verify_jwt = false

[functions.doc-share]
verify_jwt = false

[functions.stripe-actions]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
