/**
 * robots-generator — Generate optimized robots.txt based on site configuration
 * 
 * Actions:
 *   - generate: Create an optimized robots.txt from site analysis
 *   - analyze-current: Parse and score the existing robots.txt
 *   - preview: Show a diff between current and recommended robots.txt
 */
import { getServiceClient, getUserClient } from '../_shared/supabaseClient.ts'
import { corsHeaders } from '../_shared/cors.ts'
import { handleRequest, jsonOk, jsonError } from '../_shared/serveHandler.ts';

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

interface RobotsConfig {
  block_ai_bots: boolean
  block_seo_crawlers: boolean
  allow_googlebot: boolean
  allow_bingbot: boolean
  block_bad_bots: boolean
  custom_disallow: string[]
  custom_allow: string[]
  sitemap_urls: string[]
  crawl_delay?: number
}

const AI_BOTS = [
  { name: 'GPTBot', company: 'OpenAI' },
  { name: 'CCBot', company: 'Common Crawl' },
  { name: 'Google-Extended', company: 'Google (Gemini)' },
  { name: 'ClaudeBot', company: 'Anthropic' },
  { name: 'Applebot-Extended', company: 'Apple Intelligence' },
  { name: 'PerplexityBot', company: 'Perplexity AI' },
  { name: 'Bytespider', company: 'ByteDance' },
  { name: 'Diffbot', company: 'Diffbot' },
  { name: 'FacebookBot', company: 'Meta' },
  { name: 'Omgilibot', company: 'Webz.io' },
  { name: 'Amazonbot', company: 'Amazon' },
]

const BAD_BOTS = [
  'AhrefsBot', 'SemrushBot', 'DotBot', 'MJ12bot', 'BLEXBot',
  'SearchmetricsBot', 'PetalBot', 'Sogou', 'YandexBot',
]

function generateRobotsTxt(config: RobotsConfig, domain: string): string {
  const lines: string[] = [
    `# robots.txt for ${domain}`,
    `# Generated by Crawlers SEO Platform`,
    `# ${new Date().toISOString().split('T')[0]}`,
    '',
  ]

  // Main Googlebot rules
  if (config.allow_googlebot) {
    lines.push('User-agent: Googlebot')
    lines.push('Allow: /')
    for (const path of config.custom_disallow) {
      lines.push(`Disallow: ${path}`)
    }
    lines.push('')
  }

  // Bingbot
  if (config.allow_bingbot) {
    lines.push('User-agent: Bingbot')
    lines.push('Allow: /')
    for (const path of config.custom_disallow) {
      lines.push(`Disallow: ${path}`)
    }
    lines.push('')
  }

  // AI Bots
  if (config.block_ai_bots) {
    lines.push('# ── AI Crawlers (blocked) ──')
    for (const bot of AI_BOTS) {
      lines.push(`User-agent: ${bot.name}`)
      lines.push('Disallow: /')
      lines.push('')
    }
  }

  // Bad bots
  if (config.block_bad_bots) {
    lines.push('# ── SEO Crawlers / Scrapers (blocked) ──')
    for (const bot of BAD_BOTS) {
      lines.push(`User-agent: ${bot}`)
      lines.push('Disallow: /')
      lines.push('')
    }
  }

  // Default user-agent
  lines.push('User-agent: *')
  if (config.crawl_delay) {
    lines.push(`Crawl-delay: ${config.crawl_delay}`)
  }
  
  // Standard disallows
  const standardDisallow = [
    '/wp-admin/', '/wp-login.php', '/wp-json/',
    '/admin/', '/login/', '/cart/', '/checkout/',
    '/search/', '/*?s=', '/*?p=', '/tag/',
    '/wp-content/plugins/', '/trackback/',
    '/feed/', '/comments/feed/',
    ...config.custom_disallow,
  ]
  
  const uniqueDisallow = [...new Set(standardDisallow)]
  for (const path of uniqueDisallow) {
    lines.push(`Disallow: ${path}`)
  }

  for (const path of config.custom_allow) {
    lines.push(`Allow: ${path}`)
  }

  lines.push('')

  // Sitemaps
  if (config.sitemap_urls.length > 0) {
    lines.push('# ── Sitemaps ──')
    for (const url of config.sitemap_urls) {
      lines.push(`Sitemap: ${url}`)
    }
  } else {
    lines.push(`Sitemap: https://${domain}/sitemap.xml`)
    lines.push(`Sitemap: https://${domain}/sitemap_index.xml`)
  }

  return lines.join('\n')
}

function analyzeRobotsTxt(content: string): any {
  const lines = content.split('\n').map(l => l.trim())
  const issues: any[] = []
  let score = 100

  // Check for sitemap declaration
  if (!lines.some(l => l.toLowerCase().startsWith('sitemap:'))) {
    issues.push({ severity: 'high', message: 'Aucune déclaration de sitemap trouvée', fix: 'Ajoutez Sitemap: https://votre-domaine.com/sitemap.xml' })
    score -= 15
  }

  // Check AI bots blocking
  const aiBotsBlocked = AI_BOTS.filter(b => {
    const uaLine = lines.findIndex(l => l.toLowerCase().includes(b.name.toLowerCase()))
    if (uaLine < 0) return false
    return lines.slice(uaLine, uaLine + 3).some(l => l.startsWith('Disallow: /'))
  })

  if (aiBotsBlocked.length === 0) {
    issues.push({ severity: 'info', message: 'Aucun bot IA n\'est bloqué — vos contenus alimentent les LLMs', fix: 'Ajoutez des règles pour GPTBot, ClaudeBot, etc. si vous souhaitez protéger vos contenus' })
  }

  // Check if Googlebot is blocked
  const gLines = lines.findIndex(l => l.toLowerCase() === 'user-agent: googlebot')
  if (gLines >= 0 && lines.slice(gLines, gLines + 5).some(l => l === 'Disallow: /')) {
    issues.push({ severity: 'critical', message: 'Googlebot est entièrement bloqué !', fix: 'Supprimez Disallow: / pour Googlebot' })
    score -= 50
  }

  // Check for wildcard blocking everything
  const wildcardIdx = lines.findIndex(l => l === 'User-agent: *')
  if (wildcardIdx >= 0) {
    const nextLines = lines.slice(wildcardIdx + 1, wildcardIdx + 5)
    if (nextLines.includes('Disallow: /') && !nextLines.some(l => l.startsWith('Allow:'))) {
      issues.push({ severity: 'critical', message: 'Tous les bots sont bloqués par défaut (User-agent: * → Disallow: /)', fix: 'Remplacez par des règles spécifiques par bot' })
      score -= 40
    }
  }

  // Check crawl-delay
  const crawlDelay = lines.find(l => l.toLowerCase().startsWith('crawl-delay:'))
  if (crawlDelay) {
    const delay = parseInt(crawlDelay.split(':')[1])
    if (delay > 10) {
      issues.push({ severity: 'medium', message: `Crawl-delay très élevé (${delay}s) — ralentit l'indexation`, fix: 'Réduisez à 2-5 secondes ou supprimez' })
      score -= 10
    }
  }

  return {
    score: Math.max(0, score),
    total_rules: lines.filter(l => l.startsWith('Disallow:') || l.startsWith('Allow:')).length,
    user_agents: lines.filter(l => l.startsWith('User-agent:')).map(l => l.split(':')[1].trim()),
    ai_bots_blocked: aiBotsBlocked.map(b => b.name),
    ai_bots_allowed: AI_BOTS.filter(b => !aiBotsBlocked.includes(b)).map(b => b.name),
    sitemaps: lines.filter(l => l.toLowerCase().startsWith('sitemap:')).map(l => l.split(/:\s*/)[1]),
    issues,
  }
}

Deno.serve(handleRequest(async (req) => {
try {
    const { action, tracked_site_id, config, robots_content } = await req.json()

    const authHeader = req.headers.get('Authorization')
    if (!authHeader) return json({ error: 'Unauthorized' }, 401)

    const userClient = getUserClient(authHeader)
    const { data: { user }, error: userErr } = await userClient.auth.getUser()
    if (userErr || !user) return json({ error: 'Unauthorized' }, 401)
    if (!tracked_site_id) return json({ error: 'tracked_site_id required' }, 400)

    const sb = getServiceClient()
    const { data: site } = await sb.from('tracked_sites').select('domain').eq('id', tracked_site_id).single()
    if (!site) return json({ error: 'Site not found' }, 404)

    let result: any

    switch (action) {
      case 'generate': {
        const defaultConfig: RobotsConfig = {
          block_ai_bots: true,
          block_seo_crawlers: false,
          allow_googlebot: true,
          allow_bingbot: true,
          block_bad_bots: true,
          custom_disallow: [],
          custom_allow: [],
          sitemap_urls: [],
          crawl_delay: undefined,
          ...config,
        }

        // Try to detect sitemap URLs from existing data
        if (defaultConfig.sitemap_urls.length === 0) {
          const { data: sitemapData } = await sb
            .from('crawl_index_history')
            .select('sitemap_count')
            .eq('tracked_site_id', tracked_site_id)
            .limit(1)
          // Default sitemap URLs
          defaultConfig.sitemap_urls = [`https://${site.domain}/sitemap.xml`]
        }

        const robotsTxt = generateRobotsTxt(defaultConfig, site.domain)
        const analysis = analyzeRobotsTxt(robotsTxt)
        
        result = { robots_txt: robotsTxt, analysis, config: defaultConfig }
        break
      }

      case 'analyze-current': {
        if (!robots_content) {
          // Fetch robots.txt from the site
          try {
            const res = await fetch(`https://${site.domain}/robots.txt`, {
              headers: { 'User-Agent': 'CrawlersSEO/1.0' },
              signal: AbortSignal.timeout(10000),
            })
            const content = res.ok ? await res.text() : ''
            result = analyzeRobotsTxt(content || '')
            result.raw_content = content
            result.http_status = res.status
          } catch {
            result = { error: 'Could not fetch robots.txt', http_status: 0, issues: [{ severity: 'high', message: 'Impossible de récupérer le robots.txt', fix: 'Vérifiez que le fichier est accessible' }] }
          }
        } else {
          result = analyzeRobotsTxt(robots_content)
        }
        break
      }

      case 'preview': {
        // Fetch current, generate optimal, show diff
        let currentContent = ''
        try {
          const res = await fetch(`https://${site.domain}/robots.txt`, {
            headers: { 'User-Agent': 'CrawlersSEO/1.0' },
            signal: AbortSignal.timeout(10000),
          })
          currentContent = res.ok ? await res.text() : ''
        } catch { /* ignore */ }

        const optimal = generateRobotsTxt({
          block_ai_bots: true, block_seo_crawlers: false,
          allow_googlebot: true, allow_bingbot: true, block_bad_bots: true,
          custom_disallow: [], custom_allow: [],
          sitemap_urls: [`https://${site.domain}/sitemap.xml`],
          ...config,
        }, site.domain)

        const currentAnalysis = analyzeRobotsTxt(currentContent)
        const optimalAnalysis = analyzeRobotsTxt(optimal)

        result = {
          current: { content: currentContent, analysis: currentAnalysis },
          recommended: { content: optimal, analysis: optimalAnalysis },
          improvement: optimalAnalysis.score - currentAnalysis.score,
        }
        break
      }

      default:
        return json({ error: `Unknown action: ${action}` }, 400)
    }

    await sb.from('analytics_events').insert({
      user_id: user.id,
      event_type: `robots-generator:${action}`,
      event_data: { tracked_site_id },
    }).catch(() => {})

    return json(result)
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : 'Unknown error'
    console.error('[robots-generator] error:', msg)
    return json({ error: msg }, 500)
  }
})