/**
 * compute-spiral-signals — Breathing Spiral: pre-computation of dynamic spiral scores
 * 
 * Cron: every 6 hours (or triggered post-event)
 * 
 * For each active tracked_site, computes 6 signals on pending/in_progress workbench items:
 * 1. Velocity Decay — keyword position erosion over 3 weeks
 * 2. Competitor Momentum — competitors gaining positions
 * 3. Cluster Maturity — % deployed items per cluster
 * 4. GMB Urgency — local ranking/review decline
 * 5. Conversion Weight — GA4 conversion rate per URL
 * 6. Topic Saturation — penalizes content creation when topic already has many articles
 * 
 * Also auto-generates content_upgrade items for pages declining without active workbench items.
 * 
 * POST { all: true } → cron mode (all active sites)
 * POST { tracked_site_id } → single site
 */
import { getServiceClient } from '../_shared/supabaseClient.ts'
import { handleRequest, jsonOk, jsonError } from '../_shared/serveHandler.ts'
import { getAuthenticatedUser } from '../_shared/auth.ts'

const MAX_SITES_PER_RUN = 50
const VELOCITY_DECAY_WEEKS = 3
const VELOCITY_DECAY_THRESHOLD = 3 // positions lost
const COMPETITOR_GAIN_THRESHOLD = 5

Deno.serve(handleRequest(async (req) => {
  const auth = await getAuthenticatedUser(req)
  if (!auth) return jsonError('Unauthorized', 401)

  const body = await req.json().catch(() => ({}))
  const supabase = getServiceClient()

  // Determine sites to process
  let sites: { id: string; domain: string; user_id: string }[] = []

  if (body.all) {
    const { data } = await supabase
      .from('tracked_sites')
      .select('id, domain, user_id')
      .eq('is_active', true)
      .limit(MAX_SITES_PER_RUN)
    sites = data || []
  } else if (body.tracked_site_id) {
    const { data } = await supabase
      .from('tracked_sites')
      .select('id, domain, user_id')
      .eq('id', body.tracked_site_id)
      .maybeSingle()
    if (data) sites = [data]
  } else {
    const { data } = await supabase
      .from('tracked_sites')
      .select('id, domain, user_id')
      .eq('user_id', auth.userId)
      .eq('is_active', true)
    sites = data || []
  }

  let totalUpdated = 0
  let totalAutoGenerated = 0

  for (const site of sites) {
    try {
      const result = await computeSignalsForSite(supabase, site)
      totalUpdated += result.updated
      totalAutoGenerated += result.autoGenerated
    } catch (e) {
      console.error(`[compute-spiral] Error for ${site.domain}:`, e)
    }
  }

  console.log(`[compute-spiral] ✅ Done: ${sites.length} sites, ${totalUpdated} items updated, ${totalAutoGenerated} auto-generated`)

  return jsonOk({
    success: true,
    sites_processed: sites.length,
    items_updated: totalUpdated,
    items_auto_generated: totalAutoGenerated,
  })
}))

// ─── Per-site computation ─────────────────────────────────────────────

async function computeSignalsForSite(
  supabase: any,
  site: { id: string; domain: string; user_id: string },
): Promise<{ updated: number; autoGenerated: number }> {
  const cleanDomain = site.domain.replace(/^www\./, '').toLowerCase()

  // Fetch active workbench items
  const { data: items } = await supabase
    .from('architect_workbench')
    .select('id, target_url, finding_category, cluster_id, action_type')
    .eq('tracked_site_id', site.id)
    .in('status', ['pending', 'in_progress'])
    .limit(500)

  if (!items?.length) return { updated: 0, autoGenerated: 0 }

  // Parallel data fetching (7 signals + topic saturation)
  const [velocityMap, competitorMomentumMap, clusterMaturityMap, gmbScore, conversionMap, newsContextBoost, topicSaturationMap] = await Promise.all([
    computeVelocityDecay(supabase, site.id, cleanDomain),
    computeCompetitorMomentum(supabase, site.id),
    computeClusterMaturity(supabase, site.id),
    computeGmbUrgency(supabase, site.id),
    computeConversionWeight(supabase, site.id),
    computeNewsContext(supabase, site.id, site.domain),
    computeTopicSaturation(supabase, site.id, cleanDomain),
  ])

  // Update each item with individual signals + aggregated spiral_score
  let updated = 0
  for (const item of items) {
    const velocityScore = getVelocityForItem(velocityMap, item.target_url)
    const competitorScore = getCompetitorMomentumForItem(competitorMomentumMap, item.target_url, item.finding_category)
    const maturity = item.cluster_id ? (clusterMaturityMap.get(item.cluster_id) ?? 0) : 0
    const convWeight = getConversionForItem(conversionMap, item.target_url)
    const topicSat = item.cluster_id ? (topicSaturationMap.get(item.cluster_id) ?? 0) : 0

    // ═══ Spiral Score Aggregation ═══
    // Composite score (0-100) from 6 weighted signals:
    //   Velocity Decay       (0-25)  × 1.6  → max 40 pts  — declining pages need urgent attention
    //   Competitor Momentum  (0-25)  × 0.8  → max 20 pts  — external pressure
    //   Cluster Maturity     (0-100) → inverted: (100-maturity)/100 × 15 → max 15 pts — immature clusters need work
    //   GMB Urgency          (0-25)  × 0.6  → max 15 pts  — local SEO decline
    //   Conversion Weight    (0-1)   × 10   → max 10 pts  — high-converting pages get priority
    //   Topic Saturation     (0-20)  → NEGATIVE malus for content creation items in saturated clusters
    const isContentCreation = item.action_type === 'create_content' || item.finding_category === 'gap_create'
    const saturationMalus = isContentCreation ? topicSat : 0

    const spiralScore = Math.min(100, Math.max(0, Math.round(
      (velocityScore * 1.6) +
      (competitorScore * 0.8) +
      ((100 - maturity) / 100 * 15) +
      (gmbScore * 0.6) +
      (convWeight * 10) -
      saturationMalus
    )))

    const { error } = await supabase
      .from('architect_workbench')
      .update({
        velocity_decay_score: velocityScore,
        competitor_momentum_score: competitorScore,
        cluster_maturity_pct: maturity,
        gmb_urgency_score: gmbScore,
        conversion_weight: convWeight,
        spiral_score: spiralScore,
        updated_at: new Date().toISOString(),
      })
      .eq('id', item.id)

    if (!error) updated++
  }

  // Auto-generate content_upgrade for declining pages without workbench items
  const autoGenerated = await autoGenerateDeclineItems(supabase, site, velocityMap, items)

  // Update cluster_definitions maturity
  for (const [clusterId, maturity] of clusterMaturityMap) {
    await supabase
      .from('cluster_definitions')
      .update({ maturity_pct: maturity, updated_at: new Date().toISOString() })
      .eq('id', clusterId)
  }

  console.log(`[compute-spiral] ${cleanDomain}: ${updated} items updated, ${autoGenerated} auto-generated`)
  return { updated, autoGenerated }
}

// ─── Signal 1: Velocity Decay ─────────────────────────────────────────

async function computeVelocityDecay(
  supabase: any,
  trackedSiteId: string,
  domain: string,
): Promise<Map<string, number>> {
  const velocityMap = new Map<string, number>() // query → decay score (0-25)

  // Get last 3 weeks of daily positions
  const threeWeeksAgo = new Date()
  threeWeeksAgo.setDate(threeWeeksAgo.getDate() - 21)
  const dateStr = threeWeeksAgo.toISOString().split('T')[0]

  const { data: positions } = await supabase
    .from('gsc_daily_positions')
    .select('query, position, date_val')
    .eq('tracked_site_id', trackedSiteId)
    .gte('date_val', dateStr)
    .order('date_val', { ascending: true })
    .limit(1000)

  if (!positions?.length) return velocityMap

  // Group by query
  const queryPositions = new Map<string, { date: string; position: number }[]>()
  for (const p of positions) {
    const existing = queryPositions.get(p.query) || []
    existing.push({ date: p.date_val, position: p.position })
    queryPositions.set(p.query, existing)
  }

  // Detect consistent decline
  for (const [query, dataPoints] of queryPositions) {
    if (dataPoints.length < 3) continue

    // Compare first week avg vs last week avg
    const sorted = dataPoints.sort((a, b) => a.date.localeCompare(b.date))
    const firstThird = sorted.slice(0, Math.ceil(sorted.length / 3))
    const lastThird = sorted.slice(-Math.ceil(sorted.length / 3))

    const avgFirst = firstThird.reduce((s, p) => s + p.position, 0) / firstThird.length
    const avgLast = lastThird.reduce((s, p) => s + p.position, 0) / lastThird.length
    const decline = avgLast - avgFirst // positive = positions lost (worse)

    if (decline >= VELOCITY_DECAY_THRESHOLD) {
      // Score 0-25 based on severity
      const score = Math.min(25, Math.round(decline * 2.5))
      velocityMap.set(query, score)
    }
  }

  return velocityMap
}

function getVelocityForItem(velocityMap: Map<string, number>, targetUrl?: string | null): number {
  if (!targetUrl || velocityMap.size === 0) return 0
  // Return max velocity decay for any query related to this URL
  let maxScore = 0
  for (const score of velocityMap.values()) {
    if (score > maxScore) maxScore = score
  }
  // Simple heuristic: if there's any velocity decay, it affects all items proportionally
  return Math.round(maxScore * 0.5)
}

// ─── Signal 2: Competitor Momentum (per-item) ─────────────────────────
// Crosses competitor_tracked_urls.serp_positions with keyword_universe
// to find which of user's target keywords are contested by competitors.
// Returns a map: keyword → score (0-25)

async function computeCompetitorMomentum(
  supabase: any,
  trackedSiteId: string,
): Promise<Map<string, number>> {
  const momentumMap = new Map<string, number>() // keyword → pressure score

  // 1. Get all competitor SERP positions for this site
  const { data: competitors } = await supabase
    .from('competitor_tracked_urls')
    .select('competitor_domain, serp_positions')
    .eq('tracked_site_id', trackedSiteId)
    .eq('crawl_status', 'done')

  if (!competitors?.length) return momentumMap

  // 2. Get user's keyword universe for matching
  const { data: kwData } = await supabase
    .from('keyword_universe')
    .select('keyword, current_position, search_volume')
    .eq('tracked_site_id', trackedSiteId)
    .limit(200)

  if (!kwData?.length) return momentumMap

  const kwSet = new Set(kwData.map((k: any) => k.keyword.toLowerCase()))
  const userPositions = new Map<string, number>()
  for (const k of kwData) {
    userPositions.set(k.keyword.toLowerCase(), k.current_position || 100)
  }

  // 3. For each keyword, count how many competitors rank on it and how well
  const keywordPressure = new Map<string, { competitorCount: number; bestCompRank: number }>()

  for (const comp of competitors) {
    const positions = comp.serp_positions as any[] || []
    for (const pos of positions) {
      const kw = (pos.keyword || '').toLowerCase()
      if (!kwSet.has(kw)) continue
      const existing = keywordPressure.get(kw) || { competitorCount: 0, bestCompRank: 100 }
      existing.competitorCount++
      existing.bestCompRank = Math.min(existing.bestCompRank, pos.position || 100)
      keywordPressure.set(kw, existing)
    }
  }

  // 4. Compute score per keyword: more competitors + better positions = higher pressure
  for (const [kw, pressure] of keywordPressure) {
    const userPos = userPositions.get(kw) || 100
    let score = 0

    // Multi-competitor pressure: 1 comp = 5pts, 2 = 12pts, 3 = 18pts
    score += Math.min(18, pressure.competitorCount * 6)

    // Competitor rank bonus: top 3 = +7, top 10 = +4, top 20 = +2
    if (pressure.bestCompRank <= 3) score += 7
    else if (pressure.bestCompRank <= 10) score += 4
    else if (pressure.bestCompRank <= 20) score += 2

    // User is behind competitor → extra urgency
    if (userPos > pressure.bestCompRank) score = Math.min(25, score + 3)

    momentumMap.set(kw, Math.min(25, score))
  }

  if (momentumMap.size > 0) {
    console.log(`[compute-spiral] 🎯 Competitor momentum: ${momentumMap.size} keywords under pressure`)
  }

  return momentumMap
}

function getCompetitorMomentumForItem(
  momentumMap: Map<string, number>,
  targetUrl?: string | null,
  findingCategory?: string,
): number {
  if (momentumMap.size === 0) return 0

  // If item has a target URL, find best matching keyword pressure
  // For now, return the max pressure score across all keywords
  // (items are often related to the site's most important keywords)
  let maxScore = 0
  for (const score of momentumMap.values()) {
    if (score > maxScore) maxScore = score
  }

  // Scale: items with SEO-related categories get full pressure, others get partial
  const seoCategories = ['seo_fix', 'gap_create', 'content_upgrade', 'keyword_optimization', 'technical_seo']
  const isSeoRelated = findingCategory && seoCategories.some(c => findingCategory.includes(c))

  return isSeoRelated ? maxScore : Math.round(maxScore * 0.5)
}

// ─── Signal 3: Cluster Maturity ───────────────────────────────────────

async function computeClusterMaturity(
  supabase: any,
  trackedSiteId: string,
): Promise<Map<string, number>> {
  const maturityMap = new Map<string, number>()

  const { data: clusters } = await supabase
    .from('cluster_definitions')
    .select('id')
    .eq('tracked_site_id', trackedSiteId)

  if (!clusters?.length) return maturityMap

  for (const cluster of clusters) {
    const { count: total } = await supabase
      .from('architect_workbench')
      .select('id', { count: 'exact', head: true })
      .eq('cluster_id', cluster.id)

    const { count: done } = await supabase
      .from('architect_workbench')
      .select('id', { count: 'exact', head: true })
      .eq('cluster_id', cluster.id)
      .in('status', ['deployed', 'done'])

    const totalN = total || 0
    const doneN = done || 0
    const maturity = totalN > 0 ? Math.round((doneN / totalN) * 100) : 0
    maturityMap.set(cluster.id, maturity)

    // Also update cluster totals
    await supabase
      .from('cluster_definitions')
      .update({ total_items: totalN, deployed_items: doneN, maturity_pct: maturity })
      .eq('id', cluster.id)
  }

  return maturityMap
}

// ─── Signal 4: GMB Urgency ────────────────────────────────────────────

async function computeGmbUrgency(
  supabase: any,
  trackedSiteId: string,
): Promise<number> {
  // Check gmb_power_snapshots for decline
  const { data: snapshots } = await supabase
    .from('gmb_power_snapshots')
    .select('total_score, reputation_score, local_serp_score, measured_at')
    .eq('tracked_site_id', trackedSiteId)
    .order('measured_at', { ascending: false })
    .limit(4)

  if (!snapshots || snapshots.length < 2) return 0

  const latest = snapshots[0]
  const previous = snapshots[1]

  let urgency = 0

  // Total score decline
  if (latest.total_score < previous.total_score) {
    const decline = previous.total_score - latest.total_score
    urgency += Math.min(10, decline * 2)
  }

  // Reputation decline (reviews)
  if (latest.reputation_score && previous.reputation_score && latest.reputation_score < previous.reputation_score) {
    urgency += 5
  }

  // Local SERP decline
  if (latest.local_serp_score && previous.local_serp_score && latest.local_serp_score < previous.local_serp_score) {
    urgency += 5
  }

  return Math.min(20, Math.round(urgency))
}

// ─── Signal 5: Conversion Weight ──────────────────────────────────────

async function computeConversionWeight(
  supabase: any,
  trackedSiteId: string,
): Promise<Map<string, number>> {
  const convMap = new Map<string, number>() // page_path → weight (0.5 - 3.0)

  const { data: metrics } = await supabase
    .from('ga4_behavioral_metrics')
    .select('page_path, conversion_rate, engagement_rate')
    .eq('tracked_site_id', trackedSiteId)
    .order('measured_at', { ascending: false })
    .limit(200)

  if (!metrics?.length) return convMap

  // Deduplicate by page_path (keep most recent)
  const seen = new Set<string>()
  for (const m of metrics) {
    if (seen.has(m.page_path)) continue
    seen.add(m.page_path)

    const cr = m.conversion_rate || 0
    const er = m.engagement_rate || 0

    // Weight: base 1.0, boost for high conversion, slight boost for engagement
    let weight = 1.0
    if (cr > 5) weight = 2.5
    else if (cr > 2) weight = 2.0
    else if (cr > 1) weight = 1.5
    else if (cr > 0.5) weight = 1.2

    // Engagement bonus
    if (er > 70) weight *= 1.1
    else if (er < 20 && cr === 0) weight = 0.7 // Low engagement, no conversion → deprioritize

    convMap.set(m.page_path, Math.round(weight * 100) / 100)
  }

  return convMap
}

function getConversionForItem(convMap: Map<string, number>, targetUrl?: string | null): number {
  if (!targetUrl || convMap.size === 0) return 1.0

  try {
    const path = new URL(targetUrl).pathname
    return convMap.get(path) || 1.0
  } catch {
    return 1.0
  }
}

// ─── Signal 6: News Context ───────────────────────────────────────────
// Detects recent anomalies or significant external events that should
// trigger spiral contraction (defensive mode). Uses anomaly_alerts as proxy.

async function computeNewsContext(
  supabase: any,
  trackedSiteId: string,
  domain: string,
): Promise<number> {
  // Check recent high-severity anomalies (proxy for "something happened")
  const { data: recentAnomalies } = await supabase
    .from('anomaly_alerts')
    .select('severity, metric_source, change_pct')
    .eq('tracked_site_id', trackedSiteId)
    .gte('detected_at', new Date(Date.now() - 7 * 86400000).toISOString())
    .eq('is_dismissed', false)
    .order('detected_at', { ascending: false })
    .limit(10)

  if (!recentAnomalies?.length) return 0

  let newsBoost = 0

  for (const anomaly of recentAnomalies) {
    // Severity-based boost
    if (anomaly.severity === 'danger') newsBoost += 5
    else if (anomaly.severity === 'warning') newsBoost += 2

    // Large traffic drops suggest algorithm update or external event
    const changePct = Math.abs(anomaly.change_pct || 0)
    if (changePct > 30) newsBoost += 5
    else if (changePct > 15) newsBoost += 2

    // GSC-specific anomalies (index, crawl) suggest Google update
    if (anomaly.metric_source === 'gsc' && anomaly.severity === 'danger') {
      newsBoost += 3
    }
  }

  const finalBoost = Math.min(15, newsBoost)
  if (finalBoost > 0) {
    console.log(`[compute-spiral] 📰 News context boost: ${finalBoost} (${recentAnomalies.length} recent anomalies for ${domain})`)
  }
  return finalBoost
}

// ─── Signal 7: Topic Saturation ───────────────────────────────────────
// Measures how saturated each cluster is with existing CMS content.
// Returns a malus (0-20) per cluster_id. High saturation = deprioritize content creation.

async function computeTopicSaturation(
  supabase: any,
  trackedSiteId: string,
  domain: string,
): Promise<Map<string, number>> {
  const satMap = new Map<string, number>()

  // Count existing articles per cluster from iktracker_content_cache (published + drafts)
  const { data: cachedContent } = await supabase
    .from('iktracker_content_cache')
    .select('title, cluster_id, status')
    .eq('tracked_site_id', trackedSiteId)
    .eq('content_type', 'post')
    .limit(500)

  if (!cachedContent?.length) return satMap

  // Group by cluster_id and count
  const clusterCounts = new Map<string, number>()
  for (const item of cachedContent) {
    const cid = item.cluster_id
    if (!cid) continue
    clusterCounts.set(cid, (clusterCounts.get(cid) || 0) + 1)
  }

  // Also check for title-level redundancy within each cluster
  const clusterTitles = new Map<string, string[]>()
  for (const item of cachedContent) {
    const cid = item.cluster_id
    if (!cid || !item.title) continue
    const titles = clusterTitles.get(cid) || []
    titles.push(item.title.toLowerCase())
    clusterTitles.set(cid, titles)
  }

  for (const [clusterId, count] of clusterCounts) {
    let malus = 0

    // Base saturation: ≥5 articles = malus starts, ≥10 = heavy malus
    if (count >= 10) malus += 15
    else if (count >= 7) malus += 10
    else if (count >= 5) malus += 5

    // Redundancy bonus: check if titles within the cluster are too similar
    const titles = clusterTitles.get(clusterId) || []
    if (titles.length >= 3) {
      // Simple pairwise check for high overlap
      let redundantPairs = 0
      for (let i = 0; i < Math.min(titles.length, 10); i++) {
        for (let j = i + 1; j < Math.min(titles.length, 10); j++) {
          const wordsA = new Set(titles[i].split(/\s+/).filter((w: string) => w.length > 2))
          const wordsB = new Set(titles[j].split(/\s+/).filter((w: string) => w.length > 2))
          let inter = 0
          for (const w of wordsA) { if (wordsB.has(w)) inter++ }
          const sim = inter / Math.max(wordsA.size, wordsB.size)
          if (sim >= 0.5) redundantPairs++
        }
      }
      if (redundantPairs >= 3) malus += 5
    }

    if (malus > 0) {
      satMap.set(clusterId, Math.min(20, malus))
    }
  }

  if (satMap.size > 0) {
    console.log(`[compute-spiral] 🔴 Topic saturation: ${satMap.size} clusters penalized for ${domain}`)
  }

  return satMap
}

// ─── Auto-generate content_upgrade for declining pages ────────────────

async function autoGenerateDeclineItems(
  supabase: any,
  site: { id: string; domain: string; user_id: string },
  velocityMap: Map<string, number>,
  existingItems: any[],
): Promise<number> {
  if (velocityMap.size === 0) return 0

  // Get target_urls already covered by active items
  const coveredUrls = new Set(
    existingItems
      .filter(i => i.target_url)
      .map(i => i.target_url.toLowerCase())
  )

  // Find keywords with significant decline not covered by any item
  const significantDeclines = [...velocityMap.entries()]
    .filter(([, score]) => score >= 10) // Only significant declines
    .slice(0, 5) // Max 5 auto-generated per site per run

  let generated = 0

  for (const [query, decayScore] of significantDeclines) {
    // Find the URL for this query in keyword_universe
    const { data: kwData } = await supabase
      .from('keyword_universe')
      .select('target_url, cluster_id')
      .eq('domain', site.domain.replace(/^www\./, '').toLowerCase())
      .ilike('keyword', query)
      .maybeSingle()

    const targetUrl = kwData?.target_url
    if (!targetUrl || coveredUrls.has(targetUrl.toLowerCase())) continue

    // Auto-create content_upgrade item
    const severity = decayScore >= 20 ? 'danger' : 'warning'
    const { error } = await supabase
      .from('architect_workbench')
      .insert({
        tracked_site_id: site.id,
        user_id: site.user_id,
        domain: site.domain.replace(/^www\./, '').toLowerCase(),
        title: `Contenu en déclin : "${query}" (perte de positions)`,
        description: `Le keyword "${query}" perd des positions depuis 3 semaines. Mise à jour du contenu recommandée.`,
        finding_category: 'content_upgrade',
        source_type: 'crawl',
        source_function: 'compute-spiral-signals',
        severity,
        status: 'pending',
        target_url: targetUrl,
        cluster_id: kwData?.cluster_id || null,
        velocity_decay_score: decayScore,
        payload: { auto_generated: true, decay_query: query, decay_score: decayScore },
      })

    if (!error) {
      generated++
      coveredUrls.add(targetUrl.toLowerCase())
    }
  }

  return generated
}
