/**
 * compute-spiral-signals — Breathing Spiral: pre-computation of dynamic spiral scores
 * 
 * Cron: every 6 hours (or triggered post-event)
 * 
 * For each active tracked_site, computes 5 signals on pending/in_progress workbench items:
 * 1. Velocity Decay — keyword position erosion over 3 weeks
 * 2. Competitor Momentum — competitors gaining positions
 * 3. Cluster Maturity — % deployed items per cluster
 * 4. GMB Urgency — local ranking/review decline
 * 5. Conversion Weight — GA4 conversion rate per URL
 * 
 * Also auto-generates content_upgrade items for pages declining without active workbench items.
 * 
 * POST { all: true } → cron mode (all active sites)
 * POST { tracked_site_id } → single site
 */
import { getServiceClient } from '../_shared/supabaseClient.ts'
import { handleRequest, jsonOk, jsonError } from '../_shared/serveHandler.ts'
import { getAuthenticatedUser } from '../_shared/auth.ts'

const MAX_SITES_PER_RUN = 50
const VELOCITY_DECAY_WEEKS = 3
const VELOCITY_DECAY_THRESHOLD = 3 // positions lost
const COMPETITOR_GAIN_THRESHOLD = 5

Deno.serve(handleRequest(async (req) => {
  const auth = await getAuthenticatedUser(req)
  if (!auth) return jsonError('Unauthorized', 401)

  const body = await req.json().catch(() => ({}))
  const supabase = getServiceClient()

  // Determine sites to process
  let sites: { id: string; domain: string; user_id: string }[] = []

  if (body.all) {
    const { data } = await supabase
      .from('tracked_sites')
      .select('id, domain, user_id')
      .eq('is_active', true)
      .limit(MAX_SITES_PER_RUN)
    sites = data || []
  } else if (body.tracked_site_id) {
    const { data } = await supabase
      .from('tracked_sites')
      .select('id, domain, user_id')
      .eq('id', body.tracked_site_id)
      .maybeSingle()
    if (data) sites = [data]
  } else {
    const { data } = await supabase
      .from('tracked_sites')
      .select('id, domain, user_id')
      .eq('user_id', auth.userId)
      .eq('is_active', true)
    sites = data || []
  }

  let totalUpdated = 0
  let totalAutoGenerated = 0

  for (const site of sites) {
    try {
      const result = await computeSignalsForSite(supabase, site)
      totalUpdated += result.updated
      totalAutoGenerated += result.autoGenerated
    } catch (e) {
      console.error(`[compute-spiral] Error for ${site.domain}:`, e)
    }
  }

  console.log(`[compute-spiral] ✅ Done: ${sites.length} sites, ${totalUpdated} items updated, ${totalAutoGenerated} auto-generated`)

  return jsonOk({
    success: true,
    sites_processed: sites.length,
    items_updated: totalUpdated,
    items_auto_generated: totalAutoGenerated,
  })
}))

// ─── Per-site computation ─────────────────────────────────────────────

async function computeSignalsForSite(
  supabase: any,
  site: { id: string; domain: string; user_id: string },
): Promise<{ updated: number; autoGenerated: number }> {
  const cleanDomain = site.domain.replace(/^www\./, '').toLowerCase()

  // Fetch active workbench items
  const { data: items } = await supabase
    .from('architect_workbench')
    .select('id, target_url, finding_category, cluster_id, action_type')
    .eq('tracked_site_id', site.id)
    .in('status', ['pending', 'in_progress'])
    .limit(500)

  if (!items?.length) return { updated: 0, autoGenerated: 0 }

  // Parallel data fetching (6 signals)
  const [velocityMap, clusterMaturityMap, gmbScore, conversionMap, newsContextBoost] = await Promise.all([
    computeVelocityDecay(supabase, site.id, cleanDomain),
    computeClusterMaturity(supabase, site.id),
    computeGmbUrgency(supabase, site.id),
    computeConversionWeight(supabase, site.id),
    computeNewsContext(supabase, site.id, site.domain),
  ])

  // Update each item
  let updated = 0
  for (const item of items) {
    const velocityScore = getVelocityForItem(velocityMap, item.target_url)
    const competitorScore = 0 // Will be computed when competitor data is available in keyword_universe
    const maturity = item.cluster_id ? (clusterMaturityMap.get(item.cluster_id) ?? 0) : 0
    const convWeight = getConversionForItem(conversionMap, item.target_url)

    const { error } = await supabase
      .from('architect_workbench')
      .update({
        velocity_decay_score: velocityScore,
        competitor_momentum_score: competitorScore,
        cluster_maturity_pct: maturity,
        gmb_urgency_score: gmbScore,
        conversion_weight: convWeight,
        updated_at: new Date().toISOString(),
      })
      .eq('id', item.id)

    if (!error) updated++
  }

  // Auto-generate content_upgrade for declining pages without workbench items
  const autoGenerated = await autoGenerateDeclineItems(supabase, site, velocityMap, items)

  // Update cluster_definitions maturity
  for (const [clusterId, maturity] of clusterMaturityMap) {
    await supabase
      .from('cluster_definitions')
      .update({ maturity_pct: maturity, updated_at: new Date().toISOString() })
      .eq('id', clusterId)
  }

  console.log(`[compute-spiral] ${cleanDomain}: ${updated} items updated, ${autoGenerated} auto-generated`)
  return { updated, autoGenerated }
}

// ─── Signal 1: Velocity Decay ─────────────────────────────────────────

async function computeVelocityDecay(
  supabase: any,
  trackedSiteId: string,
  domain: string,
): Promise<Map<string, number>> {
  const velocityMap = new Map<string, number>() // query → decay score (0-25)

  // Get last 3 weeks of daily positions
  const threeWeeksAgo = new Date()
  threeWeeksAgo.setDate(threeWeeksAgo.getDate() - 21)
  const dateStr = threeWeeksAgo.toISOString().split('T')[0]

  const { data: positions } = await supabase
    .from('gsc_daily_positions')
    .select('query, position, date_val')
    .eq('tracked_site_id', trackedSiteId)
    .gte('date_val', dateStr)
    .order('date_val', { ascending: true })
    .limit(1000)

  if (!positions?.length) return velocityMap

  // Group by query
  const queryPositions = new Map<string, { date: string; position: number }[]>()
  for (const p of positions) {
    const existing = queryPositions.get(p.query) || []
    existing.push({ date: p.date_val, position: p.position })
    queryPositions.set(p.query, existing)
  }

  // Detect consistent decline
  for (const [query, dataPoints] of queryPositions) {
    if (dataPoints.length < 3) continue

    // Compare first week avg vs last week avg
    const sorted = dataPoints.sort((a, b) => a.date.localeCompare(b.date))
    const firstThird = sorted.slice(0, Math.ceil(sorted.length / 3))
    const lastThird = sorted.slice(-Math.ceil(sorted.length / 3))

    const avgFirst = firstThird.reduce((s, p) => s + p.position, 0) / firstThird.length
    const avgLast = lastThird.reduce((s, p) => s + p.position, 0) / lastThird.length
    const decline = avgLast - avgFirst // positive = positions lost (worse)

    if (decline >= VELOCITY_DECAY_THRESHOLD) {
      // Score 0-25 based on severity
      const score = Math.min(25, Math.round(decline * 2.5))
      velocityMap.set(query, score)
    }
  }

  return velocityMap
}

function getVelocityForItem(velocityMap: Map<string, number>, targetUrl?: string | null): number {
  if (!targetUrl || velocityMap.size === 0) return 0
  // Return max velocity decay for any query related to this URL
  let maxScore = 0
  for (const score of velocityMap.values()) {
    if (score > maxScore) maxScore = score
  }
  // Simple heuristic: if there's any velocity decay, it affects all items proportionally
  return Math.round(maxScore * 0.5)
}

// ─── Signal 3: Cluster Maturity ───────────────────────────────────────

async function computeClusterMaturity(
  supabase: any,
  trackedSiteId: string,
): Promise<Map<string, number>> {
  const maturityMap = new Map<string, number>()

  const { data: clusters } = await supabase
    .from('cluster_definitions')
    .select('id')
    .eq('tracked_site_id', trackedSiteId)

  if (!clusters?.length) return maturityMap

  for (const cluster of clusters) {
    const { count: total } = await supabase
      .from('architect_workbench')
      .select('id', { count: 'exact', head: true })
      .eq('cluster_id', cluster.id)

    const { count: done } = await supabase
      .from('architect_workbench')
      .select('id', { count: 'exact', head: true })
      .eq('cluster_id', cluster.id)
      .in('status', ['deployed', 'done'])

    const totalN = total || 0
    const doneN = done || 0
    const maturity = totalN > 0 ? Math.round((doneN / totalN) * 100) : 0
    maturityMap.set(cluster.id, maturity)

    // Also update cluster totals
    await supabase
      .from('cluster_definitions')
      .update({ total_items: totalN, deployed_items: doneN, maturity_pct: maturity })
      .eq('id', cluster.id)
  }

  return maturityMap
}

// ─── Signal 4: GMB Urgency ────────────────────────────────────────────

async function computeGmbUrgency(
  supabase: any,
  trackedSiteId: string,
): Promise<number> {
  // Check gmb_power_snapshots for decline
  const { data: snapshots } = await supabase
    .from('gmb_power_snapshots')
    .select('total_score, reputation_score, local_serp_score, measured_at')
    .eq('tracked_site_id', trackedSiteId)
    .order('measured_at', { ascending: false })
    .limit(4)

  if (!snapshots || snapshots.length < 2) return 0

  const latest = snapshots[0]
  const previous = snapshots[1]

  let urgency = 0

  // Total score decline
  if (latest.total_score < previous.total_score) {
    const decline = previous.total_score - latest.total_score
    urgency += Math.min(10, decline * 2)
  }

  // Reputation decline (reviews)
  if (latest.reputation_score && previous.reputation_score && latest.reputation_score < previous.reputation_score) {
    urgency += 5
  }

  // Local SERP decline
  if (latest.local_serp_score && previous.local_serp_score && latest.local_serp_score < previous.local_serp_score) {
    urgency += 5
  }

  return Math.min(20, Math.round(urgency))
}

// ─── Signal 5: Conversion Weight ──────────────────────────────────────

async function computeConversionWeight(
  supabase: any,
  trackedSiteId: string,
): Promise<Map<string, number>> {
  const convMap = new Map<string, number>() // page_path → weight (0.5 - 3.0)

  const { data: metrics } = await supabase
    .from('ga4_behavioral_metrics')
    .select('page_path, conversion_rate, engagement_rate')
    .eq('tracked_site_id', trackedSiteId)
    .order('measured_at', { ascending: false })
    .limit(200)

  if (!metrics?.length) return convMap

  // Deduplicate by page_path (keep most recent)
  const seen = new Set<string>()
  for (const m of metrics) {
    if (seen.has(m.page_path)) continue
    seen.add(m.page_path)

    const cr = m.conversion_rate || 0
    const er = m.engagement_rate || 0

    // Weight: base 1.0, boost for high conversion, slight boost for engagement
    let weight = 1.0
    if (cr > 5) weight = 2.5
    else if (cr > 2) weight = 2.0
    else if (cr > 1) weight = 1.5
    else if (cr > 0.5) weight = 1.2

    // Engagement bonus
    if (er > 70) weight *= 1.1
    else if (er < 20 && cr === 0) weight = 0.7 // Low engagement, no conversion → deprioritize

    convMap.set(m.page_path, Math.round(weight * 100) / 100)
  }

  return convMap
}

function getConversionForItem(convMap: Map<string, number>, targetUrl?: string | null): number {
  if (!targetUrl || convMap.size === 0) return 1.0

  try {
    const path = new URL(targetUrl).pathname
    return convMap.get(path) || 1.0
  } catch {
    return 1.0
  }
}

// ─── Signal 6: News Context ───────────────────────────────────────────
// Detects recent anomalies or significant external events that should
// trigger spiral contraction (defensive mode). Uses anomaly_alerts as proxy.

async function computeNewsContext(
  supabase: any,
  trackedSiteId: string,
  domain: string,
): Promise<number> {
  // Check recent high-severity anomalies (proxy for "something happened")
  const { data: recentAnomalies } = await supabase
    .from('anomaly_alerts')
    .select('severity, metric_source, change_pct')
    .eq('tracked_site_id', trackedSiteId)
    .gte('detected_at', new Date(Date.now() - 7 * 86400000).toISOString())
    .eq('is_dismissed', false)
    .order('detected_at', { ascending: false })
    .limit(10)

  if (!recentAnomalies?.length) return 0

  let newsBoost = 0

  for (const anomaly of recentAnomalies) {
    // Severity-based boost
    if (anomaly.severity === 'danger') newsBoost += 5
    else if (anomaly.severity === 'warning') newsBoost += 2

    // Large traffic drops suggest algorithm update or external event
    const changePct = Math.abs(anomaly.change_pct || 0)
    if (changePct > 30) newsBoost += 5
    else if (changePct > 15) newsBoost += 2

    // GSC-specific anomalies (index, crawl) suggest Google update
    if (anomaly.metric_source === 'gsc' && anomaly.severity === 'danger') {
      newsBoost += 3
    }
  }

  const finalBoost = Math.min(15, newsBoost)
  if (finalBoost > 0) {
    console.log(`[compute-spiral] 📰 News context boost: ${finalBoost} (${recentAnomalies.length} recent anomalies for ${domain})`)
  }
  return finalBoost
}

// ─── Auto-generate content_upgrade for declining pages ────────────────

async function autoGenerateDeclineItems(
  supabase: any,
  site: { id: string; domain: string; user_id: string },
  velocityMap: Map<string, number>,
  existingItems: any[],
): Promise<number> {
  if (velocityMap.size === 0) return 0

  // Get target_urls already covered by active items
  const coveredUrls = new Set(
    existingItems
      .filter(i => i.target_url)
      .map(i => i.target_url.toLowerCase())
  )

  // Find keywords with significant decline not covered by any item
  const significantDeclines = [...velocityMap.entries()]
    .filter(([, score]) => score >= 10) // Only significant declines
    .slice(0, 5) // Max 5 auto-generated per site per run

  let generated = 0

  for (const [query, decayScore] of significantDeclines) {
    // Find the URL for this query in keyword_universe
    const { data: kwData } = await supabase
      .from('keyword_universe')
      .select('target_url, cluster_id')
      .eq('domain', site.domain.replace(/^www\./, '').toLowerCase())
      .ilike('keyword', query)
      .maybeSingle()

    const targetUrl = kwData?.target_url
    if (!targetUrl || coveredUrls.has(targetUrl.toLowerCase())) continue

    // Auto-create content_upgrade item
    const severity = decayScore >= 20 ? 'danger' : 'warning'
    const { error } = await supabase
      .from('architect_workbench')
      .insert({
        tracked_site_id: site.id,
        user_id: site.user_id,
        domain: site.domain.replace(/^www\./, '').toLowerCase(),
        title: `Contenu en déclin : "${query}" (perte de positions)`,
        description: `Le keyword "${query}" perd des positions depuis 3 semaines. Mise à jour du contenu recommandée.`,
        finding_category: 'content_upgrade',
        source_type: 'crawl',
        source_function: 'compute-spiral-signals',
        severity,
        status: 'pending',
        target_url: targetUrl,
        cluster_id: kwData?.cluster_id || null,
        velocity_decay_score: decayScore,
        payload: { auto_generated: true, decay_query: query, decay_score: decayScore },
      })

    if (!error) {
      generated++
      coveredUrls.add(targetUrl.toLowerCase())
    }
  }

  return generated
}
