import { useState, useEffect, useRef } from 'react';
import { Download, Loader2, Check, Copy, Share2, Printer, X, FileSpreadsheet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { useLanguage } from '@/contexts/LanguageContext';
import { useIsMobile } from '@/hooks/use-mobile';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useSaveReport } from '@/hooks/useSaveReport';
import { CrawlResult } from '@/types/crawler';
import { GeoResult } from '@/types/geo';
import { LLMAnalysisResult } from '@/types/llm';
import { PageSpeedResult } from '@/types/pagespeed';
import { generateReportHTML, WhiteLabelBranding, SiteCrawlReportData } from './reportHtmlGenerator';

type ReportType = 'crawlers' | 'geo' | 'llm' | 'pagespeed' | 'site_crawl' | 'full';

interface ReportPreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: ReportType;
  crawlResult?: CrawlResult | null;
  geoResult?: GeoResult | null;
  llmResult?: LLMAnalysisResult | null;
  pageSpeedResult?: PageSpeedResult | null;
  siteCrawlData?: SiteCrawlReportData | null;
  currentUrl?: string;
}

const reportTranslations = {
  fr: {
    title: 'Aperçu du Rapport',
    crawlTitle: 'Rapport Crawl',
    download: 'Télécharger',
    downloadCSV: 'CSV',
    generating: 'Génération...',
    copyLink: 'Copier le lien',
    copied: 'Copié !',
    share: 'Partager',
    sharing: 'Partage...',
    shareSuccess: 'Lien généré avec succès !',
    shareError: 'Erreur lors de la génération du lien',
    pdfSuccess: 'PDF téléchargé avec succès !',
    pdfError: 'Erreur lors de la génération du PDF',
    emailSubject: 'Rapport d\'analyse Crawlers',
    emailBody: 'Bonjour,\n\nJe vous partage ce rapport d\'analyse généré par Crawlers :\n\n{link}\n\nCe lien est valide pendant 7 jours.\n\nCordialement',
  },
  en: {
    title: 'Report Preview',
    crawlTitle: 'Crawl Report',
    download: 'Download',
    downloadCSV: 'CSV',
    generating: 'Generating...',
    copyLink: 'Copy link',
    copied: 'Copied!',
    share: 'Share',
    sharing: 'Sharing...',
    shareSuccess: 'Link generated successfully!',
    shareError: 'Error generating share link',
    pdfSuccess: 'PDF downloaded successfully!',
    pdfError: 'Error generating PDF',
    emailSubject: 'Crawlers Analysis Report',
    emailBody: 'Hello,\n\nI\'m sharing this analysis report generated by Crawlers:\n\n{link}\n\nThis link is valid for 7 days.\n\nBest regards',
  },
  es: {
    title: 'Vista previa del informe',
    download: 'Descargar',
    generating: 'Generando...',
    copyLink: 'Copiar enlace',
    copied: '¡Copiado!',
    share: 'Compartir',
    sharing: 'Compartiendo...',
    shareSuccess: '¡Enlace generado con éxito!',
    shareError: 'Error al generar el enlace',
    pdfSuccess: '¡PDF descargado con éxito!',
    pdfError: 'Error al generar el PDF',
    emailSubject: 'Informe de análisis Crawlers',
    emailBody: 'Hola,\n\nComparto este informe de análisis generado por Crawlers:\n\n{link}\n\nEste enlace es válido durante 7 días.\n\nSaludos',
  },
};

export function ReportPreviewModal({
  isOpen,
  onClose,
  type,
  crawlResult,
  geoResult,
  llmResult,
  pageSpeedResult,
  siteCrawlData,
  currentUrl,
}: ReportPreviewModalProps) {
  const { language } = useLanguage();
  const { profile, user } = useAuth();
  const isMobile = useIsMobile();
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [isCopying, setIsCopying] = useState(false);
  const [isEmailing, setIsEmailing] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const { saveReport } = useSaveReport();
  const hasSavedRef = useRef<string | null>(null);

  const t = reportTranslations[language as keyof typeof reportTranslations] || reportTranslations.fr;

  // For 'full' type, determine which result to use as primary for single-type operations
  const getEffectiveType = (): 'crawlers' | 'geo' | 'llm' | 'pagespeed' | 'site_crawl' => {
    if (type === 'site_crawl') return 'site_crawl';
    if (type !== 'full') return type as 'crawlers' | 'geo' | 'llm' | 'pagespeed';
    if (crawlResult) return 'crawlers';
    if (geoResult) return 'geo';
    if (llmResult) return 'llm';
    if (pageSpeedResult) return 'pagespeed';
    return 'crawlers';
  };

  const effectiveType = getEffectiveType();

  // For 'full' type, check if we have multiple results
  const hasMultipleResults = [crawlResult, geoResult, llmResult, pageSpeedResult].filter(Boolean).length > 1;
  const useFullType = type === 'full' && hasMultipleResults;

  const getData = (): any => {
    if (type === 'site_crawl') return siteCrawlData || null;
    
    // For full type with multiple results, return all data
    if (useFullType) {
      return {
        crawlResult,
        geoResult,
        llmResult,
        pageSpeedResult,
      };
    }
    
    // Otherwise return single result
    switch (effectiveType) {
      case 'crawlers':
        return crawlResult || null;
      case 'geo':
        return geoResult || null;
      case 'llm':
        return llmResult || null;
      case 'pagespeed':
        return pageSpeedResult || null;
      default:
        return null;
    }
  };

  const getUrl = (): string => {
    if (currentUrl) return currentUrl;
    if (type === 'site_crawl') return siteCrawlData?.domain || '';
    switch (effectiveType) {
      case 'crawlers':
        return crawlResult?.url || '';
      case 'geo':
        return geoResult?.url || '';
      case 'llm':
        return llmResult?.domain || '';
      case 'pagespeed':
        return pageSpeedResult?.url || '';
      default:
        return '';
    }
  };

  const data = getData();
  const url = getUrl();

  // Check if we have any data at all
  const hasAnyData = Boolean(crawlResult || geoResult || llmResult || pageSpeedResult || siteCrawlData);

  // Auto-save report for authenticated users when modal opens
  useEffect(() => {
    if (!isOpen || !user || !hasAnyData) return;
    const saveKey = `${url}-${effectiveType}`;
    if (hasSavedRef.current === saveKey) return;
    hasSavedRef.current = saveKey;

    const titleMap: Record<string, Record<string, string>> = {
      crawlers: { fr: 'Crawlers IA', en: 'AI Crawlers', es: 'Crawlers IA' },
      geo: { fr: 'Analyse GEO', en: 'GEO Analysis', es: 'Análisis GEO' },
      llm: { fr: 'Visibilité LLM', en: 'LLM Visibility', es: 'Visibilidad LLM' },
      pagespeed: { fr: 'PageSpeed', en: 'PageSpeed', es: 'PageSpeed' },
      site_crawl: { fr: 'Audit Multi-Pages', en: 'Multi-Page Audit', es: 'Auditoría Multi-Páginas' },
    };
    const domain = (() => { try { return new URL(url.startsWith('http') ? url : `https://${url}`).hostname; } catch { return url; } })();
    const label = titleMap[effectiveType]?.[language] || effectiveType;

    saveReport({
      reportType: effectiveType as any,
      title: `${label} – ${domain}`,
      url,
      reportData: data,
    });
  }, [isOpen, user, url, effectiveType]);

  // White-label branding
  const branding: WhiteLabelBranding | undefined =
    profile?.plan_type === 'agency_pro' && (profile.agency_logo_url || profile.agency_primary_color)
      ? { logoUrl: profile.agency_logo_url, primaryColor: profile.agency_primary_color }
      : undefined;

  if (!hasAnyData) return null;

  // Generate HTML with appropriate type
  const reportType = useFullType ? 'full' : effectiveType;
  const htmlContent = generateReportHTML(reportType, data, url, language, branding);

  // Get single-result data for the effective type (PDF/share always use single type)
  const getSingleResultData = (): any => {
    switch (effectiveType) {
      case 'crawlers': return crawlResult || null;
      case 'geo': return geoResult || null;
      case 'llm': return llmResult || null;
      case 'pagespeed': return pageSpeedResult || null;
      default: return null;
    }
  };

  const handleDownloadPDF = async () => {
    setIsGeneratingPDF(true);
    try {
      // Use the same HTML as the preview for consistent output
      const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
      const link = document.createElement('a');
      const domain = (() => { try { return new URL(url.startsWith('http') ? url : `https://${url}`).hostname; } catch { return 'report'; } })();
      const { getReportFilename } = await import('@/utils/reportFilename');
      link.href = URL.createObjectURL(blob);
      link.download = getReportFilename(domain, effectiveType as any, 'html');
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
      
    } catch (error) {
      console.error('Download error:', error);
      toast.error(t.pdfError);
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const generateShareLink = async (): Promise<string | null> => {
    try {
      const { data: responseData, error } = await supabase.functions.invoke('share-report', {
        body: {
          type: effectiveType,
          url,
          data: getSingleResultData(),
          language,
        },
      });

      if (error) throw error;

      if (responseData?.shareId) {
        let temporaryLink = `https://crawlers.fr/temporarylink/${responseData.shareId}`;
        if (user?.id) temporaryLink += `?ref=${user.id}`;
        return temporaryLink;
      }
      return null;
    } catch (error) {
      console.error('Share error:', error);
      throw error;
    }
  };

  const handleCopyLink = async () => {
    setIsCopying(true);
    try {
      let linkToCopy = shareUrl;
      
      if (!linkToCopy) {
        linkToCopy = await generateShareLink();
        if (linkToCopy) {
          setShareUrl(linkToCopy);
        }
      }

      if (linkToCopy) {
        await navigator.clipboard.writeText(linkToCopy);
        setCopied(true);
        toast.success(t.shareSuccess);
        setTimeout(() => setCopied(false), 2000);
      }
    } catch (error) {
      console.error('Copy error:', error);
      toast.error(t.shareError);
    } finally {
      setIsCopying(false);
    }
  };

  const handleShare = async () => {
    setIsEmailing(true);
    try {
      let linkToShare = shareUrl;
      
      if (!linkToShare) {
        linkToShare = await generateShareLink();
        if (linkToShare) {
          setShareUrl(linkToShare);
        }
      }

      if (linkToShare) {
        const emailBody = t.emailBody.replace('{link}', linkToShare);
        const mailtoUrl = `mailto:?subject=${encodeURIComponent(t.emailSubject)}&body=${encodeURIComponent(emailBody)}`;
        window.open(mailtoUrl, '_blank');
        toast.success(t.shareSuccess);
      }
    } catch (error) {
      console.error('Share error:', error);
      toast.error(t.shareError);
    } finally {
      setIsEmailing(false);
    }
  };

  const handlePrint = () => {
    const iframe = document.createElement('iframe');
    iframe.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:none;';
    document.body.appendChild(iframe);
    const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
    if (!iframeDoc || !iframe.contentWindow) return;
    iframeDoc.open();
    iframeDoc.write(htmlContent);
    iframeDoc.close();
    setTimeout(() => {
      iframe.contentWindow?.print();
      setTimeout(() => document.body.removeChild(iframe), 1000);
    }, 500);
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="max-w-6xl max-h-[95vh] overflow-hidden flex flex-col p-0 [&>button]:hidden" onPointerDownOutside={(e) => e.preventDefault()} onInteractOutside={(e) => e.preventDefault()}>
        {/* Header with actions */}
        <div className="flex items-center justify-between px-4 md:px-6 py-3 md:py-4 border-b border-border bg-card w-full shrink-0">
          {!isMobile && <h2 className="text-lg font-semibold shrink-0">{t.title}</h2>}
          <div className="flex items-center gap-2 md:gap-3 ml-auto">
            <Button
              onClick={handleDownloadPDF}
              disabled={isGeneratingPDF}
              size={isMobile ? 'icon' : 'default'}
              className={isMobile ? 'bg-primary hover:bg-primary/90' : 'gap-2 bg-primary hover:bg-primary/90'}
            >
              {isGeneratingPDF ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Download className="h-4 w-4" />
              )}
              {!isMobile && (isGeneratingPDF ? t.generating : t.download)}
            </Button>
            <Button
              onClick={handlePrint}
              variant="outline"
              size={isMobile ? 'icon' : 'default'}
              className={isMobile ? '' : 'gap-2'}
            >
              <Printer className="h-4 w-4" />
              {!isMobile && (language === 'fr' ? 'Imprimer' : language === 'es' ? 'Imprimir' : 'Print')}
            </Button>
            <Button
              onClick={handleCopyLink}
              disabled={isCopying}
              variant="outline"
              size={isMobile ? 'icon' : 'default'}
              className={isMobile ? '' : 'gap-2'}
            >
              {isCopying ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : copied ? (
                <Check className="h-4 w-4 text-success" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
              {!isMobile && (copied ? t.copied : t.copyLink)}
            </Button>
            <Button
              onClick={handleShare}
              disabled={isEmailing}
              variant="outline"
              size={isMobile ? 'icon' : 'default'}
              className={isMobile ? '' : 'gap-2'}
            >
              {isEmailing ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Share2 className="h-4 w-4" />
              )}
              {!isMobile && t.share}
            </Button>
            <Button
              onClick={onClose}
              variant="ghost"
              size="icon"
              className="ml-1 md:ml-2"
            >
              <X className="h-5 w-5" />
            </Button>
          </div>
        </div>

        {/* Share link display */}
        {shareUrl && (
          <div className="px-6 py-3 bg-muted/50 border-b border-border">
            <p className="text-xs text-muted-foreground mb-2">{t.copyLink}</p>
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={shareUrl}
                readOnly
                className="flex-1 px-3 py-2 text-sm bg-background border border-border rounded-md font-mono"
              />
              <Button
                onClick={handleCopyLink}
                variant="outline"
                size="sm"
                className="gap-2"
              >
                {copied ? (
                  <Check className="h-4 w-4 text-success" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
                {copied ? t.copied : t.copyLink}
              </Button>
            </div>
          </div>
        )}

        {/* HTML Preview */}
        <div className="flex-1 overflow-auto bg-muted/30">
          <iframe
            srcDoc={htmlContent}
            className="w-full h-full min-h-[600px]"
            title="Report Preview"
          />
        </div>
      </DialogContent>
    </Dialog>
  );
}
