import { useState } from 'react';
import { Download, Loader2, Check, Copy, Mail } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { useLanguage } from '@/contexts/LanguageContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { CrawlResult } from '@/types/crawler';
import { GeoResult } from '@/types/geo';
import { LLMAnalysisResult } from '@/types/llm';
import { PageSpeedResult } from '@/types/pagespeed';
import { generateReportHTML } from './reportHtmlGenerator';
import { generatePDF } from './pdfGenerator';

type ReportType = 'crawlers' | 'geo' | 'llm' | 'pagespeed' | 'full';

interface ReportPreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: ReportType;
  crawlResult?: CrawlResult | null;
  geoResult?: GeoResult | null;
  llmResult?: LLMAnalysisResult | null;
  pageSpeedResult?: PageSpeedResult | null;
  currentUrl?: string;
}

const reportTranslations = {
  fr: {
    title: 'Aperçu du Rapport',
    download: 'Télécharger',
    generating: 'Génération...',
    copyLink: 'Copier le lien',
    copied: 'Copié !',
    share: 'Partager',
    sharing: 'Partage...',
    shareSuccess: 'Lien généré avec succès !',
    shareError: 'Erreur lors de la génération du lien',
    pdfSuccess: 'PDF téléchargé avec succès !',
    pdfError: 'Erreur lors de la génération du PDF',
    emailSubject: 'Rapport d\'analyse Crawlers',
    emailBody: 'Bonjour,\n\nJe vous partage ce rapport d\'analyse généré par Crawlers :\n\n{link}\n\nCe lien est valide pendant 7 jours.\n\nCordialement',
  },
  en: {
    title: 'Report Preview',
    download: 'Download',
    generating: 'Generating...',
    copyLink: 'Copy link',
    copied: 'Copied!',
    share: 'Share',
    sharing: 'Sharing...',
    shareSuccess: 'Link generated successfully!',
    shareError: 'Error generating share link',
    pdfSuccess: 'PDF downloaded successfully!',
    pdfError: 'Error generating PDF',
    emailSubject: 'Crawlers Analysis Report',
    emailBody: 'Hello,\n\nI\'m sharing this analysis report generated by Crawlers:\n\n{link}\n\nThis link is valid for 7 days.\n\nBest regards',
  },
  es: {
    title: 'Vista previa del informe',
    download: 'Descargar',
    generating: 'Generando...',
    copyLink: 'Copiar enlace',
    copied: '¡Copiado!',
    share: 'Compartir',
    sharing: 'Compartiendo...',
    shareSuccess: '¡Enlace generado con éxito!',
    shareError: 'Error al generar el enlace',
    pdfSuccess: '¡PDF descargado con éxito!',
    pdfError: 'Error al generar el PDF',
    emailSubject: 'Informe de análisis Crawlers',
    emailBody: 'Hola,\n\nComparto este informe de análisis generado por Crawlers:\n\n{link}\n\nEste enlace es válido durante 7 días.\n\nSaludos',
  },
};

export function ReportPreviewModal({
  isOpen,
  onClose,
  type,
  crawlResult,
  geoResult,
  llmResult,
  pageSpeedResult,
  currentUrl,
}: ReportPreviewModalProps) {
  const { language } = useLanguage();
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const t = reportTranslations[language as keyof typeof reportTranslations] || reportTranslations.fr;

  // For 'full' type, determine which result to use as primary
  const getEffectiveType = (): 'crawlers' | 'geo' | 'llm' | 'pagespeed' => {
    if (type !== 'full') return type;
    if (crawlResult) return 'crawlers';
    if (geoResult) return 'geo';
    if (llmResult) return 'llm';
    if (pageSpeedResult) return 'pagespeed';
    return 'crawlers';
  };

  const effectiveType = getEffectiveType();

  const getData = (): CrawlResult | GeoResult | LLMAnalysisResult | PageSpeedResult | null => {
    switch (effectiveType) {
      case 'crawlers':
        return crawlResult || null;
      case 'geo':
        return geoResult || null;
      case 'llm':
        return llmResult || null;
      case 'pagespeed':
        return pageSpeedResult || null;
      default:
        return null;
    }
  };

  const getUrl = (): string => {
    if (currentUrl) return currentUrl;
    switch (effectiveType) {
      case 'crawlers':
        return crawlResult?.url || '';
      case 'geo':
        return geoResult?.url || '';
      case 'llm':
        return llmResult?.domain || '';
      case 'pagespeed':
        return pageSpeedResult?.url || '';
      default:
        return '';
    }
  };

  const data = getData();
  const url = getUrl();

  if (!data) return null;

  const htmlContent = generateReportHTML(effectiveType, data, url, language);

  const handleDownloadPDF = async () => {
    setIsGeneratingPDF(true);
    try {
      await generatePDF(effectiveType, data, url, language);
      toast.success(t.pdfSuccess);
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error(t.pdfError);
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const generateShareLink = async (): Promise<string | null> => {
    try {
      const { data: responseData, error } = await supabase.functions.invoke('share-report', {
        body: {
          type: effectiveType,
          url,
          data,
          language,
        },
      });

      if (error) throw error;

      if (responseData?.shareId) {
        const temporaryLink = `https://crawlers.fr/temporaryreport/${responseData.shareId}`;
        return temporaryLink;
      }
      return null;
    } catch (error) {
      console.error('Share error:', error);
      throw error;
    }
  };

  const handleCopyLink = async () => {
    setIsSharing(true);
    try {
      let linkToCopy = shareUrl;
      
      if (!linkToCopy) {
        linkToCopy = await generateShareLink();
        if (linkToCopy) {
          setShareUrl(linkToCopy);
        }
      }

      if (linkToCopy) {
        await navigator.clipboard.writeText(linkToCopy);
        setCopied(true);
        toast.success(t.shareSuccess);
        setTimeout(() => setCopied(false), 2000);
      }
    } catch (error) {
      console.error('Copy error:', error);
      toast.error(t.shareError);
    } finally {
      setIsSharing(false);
    }
  };

  const handleShare = async () => {
    setIsSharing(true);
    try {
      let linkToShare = shareUrl;
      
      if (!linkToShare) {
        linkToShare = await generateShareLink();
        if (linkToShare) {
          setShareUrl(linkToShare);
        }
      }

      if (linkToShare) {
        const emailBody = t.emailBody.replace('{link}', linkToShare);
        const mailtoUrl = `mailto:?subject=${encodeURIComponent(t.emailSubject)}&body=${encodeURIComponent(emailBody)}`;
        window.open(mailtoUrl, '_blank');
        toast.success(t.shareSuccess);
      }
    } catch (error) {
      console.error('Share error:', error);
      toast.error(t.shareError);
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-5xl max-h-[95vh] overflow-hidden flex flex-col p-0">
        {/* Header with actions */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-card">
          <h2 className="text-lg font-semibold">{t.title}</h2>
          <div className="flex items-center gap-3">
            <Button
              onClick={handleDownloadPDF}
              disabled={isGeneratingPDF}
              className="gap-2 bg-primary hover:bg-primary/90"
            >
              {isGeneratingPDF ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Download className="h-4 w-4" />
              )}
              {isGeneratingPDF ? t.generating : t.download}
            </Button>
            <Button
              onClick={handleCopyLink}
              disabled={isSharing}
              variant="outline"
              className="gap-2"
            >
              {isSharing && !shareUrl ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : copied ? (
                <Check className="h-4 w-4 text-success" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
              {copied ? t.copied : t.copyLink}
            </Button>
            <Button
              onClick={handleShare}
              disabled={isSharing}
              variant="outline"
              className="gap-2"
            >
              {isSharing && !shareUrl ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Mail className="h-4 w-4" />
              )}
              {t.share}
            </Button>
          </div>
        </div>

        {/* HTML Preview */}
        <div className="flex-1 overflow-auto bg-muted/30">
          <iframe
            srcDoc={htmlContent}
            className="w-full h-full min-h-[600px]"
            title="Report Preview"
          />
        </div>
      </DialogContent>
    </Dialog>
  );
}
