// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Qui suis-je",
  description: "Retourne l'identit\xE9 de l'utilisateur Crawlers connect\xE9 (id, email, client OAuth).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list_my_sites.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_sites_default = defineTool2({
  name: "list_my_sites",
  title: "Lister mes sites",
  description: "Liste les sites Crawlers suivis par l'utilisateur connect\xE9 (domaine, dernier audit, score EEAT).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tracked_sites").select("id, domain, brand_name, market_sector, eeat_score, last_audit_at, business_model").order("last_audit_at", { ascending: false, nullsFirst: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    const summary = rows.length ? rows.map((r) => `- ${r.domain} \xB7 EEAT ${r.eeat_score ?? "\u2014"} \xB7 ${r.last_audit_at ?? "jamais audit\xE9"}`).join("\n") : "Aucun site suivi.";
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { sites: rows }
    };
  }
});

// src/lib/mcp/tools/get_site_audit.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_site_audit_default = defineTool3({
  name: "get_site_audit",
  title: "Dernier audit d'un site",
  description: "Renvoie le dernier audit SEO/GEO d'un site suivi par l'utilisateur, \xE0 partir de son domaine.",
  inputSchema: {
    domain: z.string().min(3).describe("Nom de domaine du site (ex: crawlers.fr)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ domain }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const normalized = domain.replace(/^https?:\/\//, "").replace(/\/.*$/, "").toLowerCase();
    const { data: site, error: siteErr } = await supabase.from("tracked_sites").select("id, domain, brand_name, eeat_score, last_audit_at").ilike("domain", `%${normalized}%`).maybeSingle();
    if (siteErr || !site) {
      return { content: [{ type: "text", text: `Aucun site trouv\xE9 pour "${domain}".` }], isError: true };
    }
    const { data: audit } = await supabase.from("audits").select("id, created_at, score, geo_score, results").eq("tracked_site_id", site.id).order("created_at", { ascending: false }).limit(1).maybeSingle();
    const payload = { site, latest_audit: audit ?? null };
    return {
      content: [
        {
          type: "text",
          text: audit ? `Site ${site.domain} \xB7 SEO ${audit.score ?? "\u2014"} \xB7 GEO ${audit.geo_score ?? "\u2014"} \xB7 audit du ${audit.created_at}.` : `Site ${site.domain} suivi mais aucun audit disponible.`
        }
      ],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tutlimtasnjabdfhpewu";
var mcp_default = defineMcp({
  name: "crawlers-mcp",
  title: "Crawlers \u2014 Agent Int\xE9grations",
  version: "0.1.0",
  instructions: "Serveur MCP officiel de Crawlers.fr. Utilise `whoami` pour v\xE9rifier la connexion, `list_my_sites` pour lister les sites suivis de l'utilisateur, et `get_site_audit` pour r\xE9cup\xE9rer le dernier audit SEO/GEO d'un site donn\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_sites_default, get_site_audit_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
